[project]
name = "blog_publisher"
version = "0.1.0"
description = "在用户输入 'blog+文章名' 时，自动将 Obsidian 本地目录下的指定 Markdown 文件复制到指定目录，处理图片链接并复制图片到目标文件夹，然后将更改推送到 GitHub。"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
]
